export function addDays(dirtyDate: any, dirtyAmount: any): any;
export function addHours(dirtyDate: any, dirtyAmount: any): any;
export function addISOYears(dirtyDate: any, dirtyAmount: any): any;
export function addMilliseconds(dirtyDate: any, dirtyAmount: any): any;
export function addMinutes(dirtyDate: any, dirtyAmount: any): any;
export function addMonths(dirtyDate: any, dirtyAmount: any): any;
export function addQuarters(dirtyDate: any, dirtyAmount: any): any;
export function addSeconds(dirtyDate: any, dirtyAmount: any): any;
export function addWeeks(dirtyDate: any, dirtyAmount: any): any;
export function addYears(dirtyDate: any, dirtyAmount: any): any;
export function areRangesOverlapping(dirtyInitialRangeStartDate: any, dirtyInitialRangeEndDate: any, dirtyComparedRangeStartDate: any, dirtyComparedRangeEndDate: any): any;
export function closestIndexTo(dirtyDateToCompare: any, dirtyDatesArray: any): any;
export function closestTo(dirtyDateToCompare: any, dirtyDatesArray: any): any;
export function compareAsc(dirtyDateLeft: any, dirtyDateRight: any): any;
export function compareDesc(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInCalendarDays(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInCalendarISOWeeks(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInCalendarISOYears(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInCalendarMonths(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInCalendarQuarters(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInCalendarWeeks(dirtyDateLeft: any, dirtyDateRight: any, dirtyOptions: any): any;
export function differenceInCalendarYears(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInDays(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInHours(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInISOYears(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInMilliseconds(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInMinutes(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInMonths(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInQuarters(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInSeconds(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInWeeks(dirtyDateLeft: any, dirtyDateRight: any): any;
export function differenceInYears(dirtyDateLeft: any, dirtyDateRight: any): any;
export function distanceInWords(dirtyDateToCompare: any, dirtyDate: any, dirtyOptions: any): any;
export function distanceInWordsStrict(dirtyDateToCompare: any, dirtyDate: any, dirtyOptions: any): any;
export function distanceInWordsToNow(dirtyDate: any, dirtyOptions: any): any;
export function eachDay(dirtyStartDate: any, dirtyEndDate: any, dirtyStep: any): any;
export function endOfDay(dirtyDate: any): any;
export function endOfHour(dirtyDate: any): any;
export function endOfISOWeek(dirtyDate: any): any;
export function endOfISOYear(dirtyDate: any): any;
export function endOfMinute(dirtyDate: any): any;
export function endOfMonth(dirtyDate: any): any;
export function endOfQuarter(dirtyDate: any): any;
export function endOfSecond(dirtyDate: any): any;
export function endOfToday(): any;
export function endOfTomorrow(): any;
export function endOfWeek(dirtyDate: any, dirtyOptions: any): any;
export function endOfYear(dirtyDate: any): any;
export function endOfYesterday(): any;
export function format(dirtyDate: any, dirtyFormatStr: any, dirtyOptions: any): any;
export function getDate(dirtyDate: any): any;
export function getDay(dirtyDate: any): any;
export function getDayOfYear(dirtyDate: any): any;
export function getDaysInMonth(dirtyDate: any): any;
export function getDaysInYear(dirtyDate: any): any;
export function getHours(dirtyDate: any): any;
export function getISODay(dirtyDate: any): any;
export function getISOWeek(dirtyDate: any): any;
export function getISOWeeksInYear(dirtyDate: any): any;
export function getISOYear(dirtyDate: any): any;
export function getMilliseconds(dirtyDate: any): any;
export function getMinutes(dirtyDate: any): any;
export function getMonth(dirtyDate: any): any;
export function getOverlappingDaysInRanges(dirtyInitialRangeStartDate: any, dirtyInitialRangeEndDate: any, dirtyComparedRangeStartDate: any, dirtyComparedRangeEndDate: any): any;
export function getQuarter(dirtyDate: any): any;
export function getSeconds(dirtyDate: any): any;
export function getTime(dirtyDate: any): any;
export function getYear(dirtyDate: any): any;
export function isAfter(dirtyDate: any, dirtyDateToCompare: any): any;
export function isBefore(dirtyDate: any, dirtyDateToCompare: any): any;
export function isDate(argument: any): any;
export function isEqual(dirtyLeftDate: any, dirtyRightDate: any): any;
export function isFirstDayOfMonth(dirtyDate: any): any;
export function isFriday(dirtyDate: any): any;
export function isFuture(dirtyDate: any): any;
export function isLastDayOfMonth(dirtyDate: any): any;
export function isLeapYear(dirtyDate: any): any;
export function isMonday(dirtyDate: any): any;
export function isPast(dirtyDate: any): any;
export function isSameDay(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameHour(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameISOWeek(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameISOYear(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameMinute(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameMonth(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameQuarter(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameSecond(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSameWeek(dirtyDateLeft: any, dirtyDateRight: any, dirtyOptions: any): any;
export function isSameYear(dirtyDateLeft: any, dirtyDateRight: any): any;
export function isSaturday(dirtyDate: any): any;
export function isSunday(dirtyDate: any): any;
export function isThisHour(dirtyDate: any): any;
export function isThisISOWeek(dirtyDate: any): any;
export function isThisISOYear(dirtyDate: any): any;
export function isThisMinute(dirtyDate: any): any;
export function isThisMonth(dirtyDate: any): any;
export function isThisQuarter(dirtyDate: any): any;
export function isThisSecond(dirtyDate: any): any;
export function isThisWeek(dirtyDate: any, dirtyOptions: any): any;
export function isThisYear(dirtyDate: any): any;
export function isThursday(dirtyDate: any): any;
export function isToday(dirtyDate: any): any;
export function isTomorrow(dirtyDate: any): any;
export function isTuesday(dirtyDate: any): any;
export function isValid(dirtyDate: any): any;
export function isWednesday(dirtyDate: any): any;
export function isWeekend(dirtyDate: any): any;
export function isWithinRange(dirtyDate: any, dirtyStartDate: any, dirtyEndDate: any): any;
export function isYesterday(dirtyDate: any): any;
export function lastDayOfISOWeek(dirtyDate: any): any;
export function lastDayOfISOYear(dirtyDate: any): any;
export function lastDayOfMonth(dirtyDate: any): any;
export function lastDayOfQuarter(dirtyDate: any): any;
export function lastDayOfWeek(dirtyDate: any, dirtyOptions: any): any;
export function lastDayOfYear(dirtyDate: any): any;
export function max(...args: any[]): any;
export function min(...args: any[]): any;
export function parse(argument: any, dirtyOptions: any): any;
export function setDate(dirtyDate: any, dirtyDayOfMonth: any): any;
export function setDay(dirtyDate: any, dirtyDay: any, dirtyOptions: any): any;
export function setDayOfYear(dirtyDate: any, dirtyDayOfYear: any): any;
export function setHours(dirtyDate: any, dirtyHours: any): any;
export function setISODay(dirtyDate: any, dirtyDay: any): any;
export function setISOWeek(dirtyDate: any, dirtyISOWeek: any): any;
export function setISOYear(dirtyDate: any, dirtyISOYear: any): any;
export function setMilliseconds(dirtyDate: any, dirtyMilliseconds: any): any;
export function setMinutes(dirtyDate: any, dirtyMinutes: any): any;
export function setMonth(dirtyDate: any, dirtyMonth: any): any;
export function setQuarter(dirtyDate: any, dirtyQuarter: any): any;
export function setSeconds(dirtyDate: any, dirtySeconds: any): any;
export function setYear(dirtyDate: any, dirtyYear: any): any;
export function startOfDay(dirtyDate: any): any;
export function startOfHour(dirtyDate: any): any;
export function startOfISOWeek(dirtyDate: any): any;
export function startOfISOYear(dirtyDate: any): any;
export function startOfMinute(dirtyDate: any): any;
export function startOfMonth(dirtyDate: any): any;
export function startOfQuarter(dirtyDate: any): any;
export function startOfSecond(dirtyDate: any): any;
export function startOfToday(): any;
export function startOfTomorrow(): any;
export function startOfWeek(dirtyDate: any, dirtyOptions: any): any;
export function startOfYear(dirtyDate: any): any;
export function startOfYesterday(): any;
export function subDays(dirtyDate: any, dirtyAmount: any): any;
export function subHours(dirtyDate: any, dirtyAmount: any): any;
export function subISOYears(dirtyDate: any, dirtyAmount: any): any;
export function subMilliseconds(dirtyDate: any, dirtyAmount: any): any;
export function subMinutes(dirtyDate: any, dirtyAmount: any): any;
export function subMonths(dirtyDate: any, dirtyAmount: any): any;
export function subQuarters(dirtyDate: any, dirtyAmount: any): any;
export function subSeconds(dirtyDate: any, dirtyAmount: any): any;
export function subWeeks(dirtyDate: any, dirtyAmount: any): any;
export function subYears(dirtyDate: any, dirtyAmount: any): any;